import { loadProfile, loadSymptoms, loadMindEntries } from '../utils/storage';
import './DoctorReport.css';

const DISCLAIMER = "⚕️ DISCLAIMER: This report is generated by BodyMind AI for informational purposes only. It is NOT a medical prescription, diagnosis, or substitute for professional medical advice. Always consult a qualified healthcare provider.";

export default function DoctorReport({ onClose }) {
  const profile = loadProfile() || {};
  const symptoms = loadSymptoms();
  const mindEntries = loadMindEntries();
  const now = new Date();
  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);

  const recentSymptoms = symptoms.filter(s => new Date(s.date) >= sevenDaysAgo);
  const recentMind = mindEntries.slice(0, 7);

  // Aggregate mind averages
  const mindAvg = recentMind.length > 0 ? {
    mood: (recentMind.reduce((a,m) => a + m.mood, 0) / recentMind.length).toFixed(1),
    sleep: (recentMind.reduce((a,m) => a + m.sleep, 0) / recentMind.length).toFixed(1),
    stress: (recentMind.reduce((a,m) => a + m.stress, 0) / recentMind.length).toFixed(1),
  } : null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="report-overlay">
      <div className="report-container fade-in">
        {/* Action bar */}
        <div className="report-actions no-print">
          <div className="report-actions-left">
            <button className="close-btn" onClick={onClose} id="report-close-btn">✕ Close</button>
          </div>
          <div className="report-actions-right">
            <button className="btn-primary" onClick={handlePrint} id="report-print-btn">
              🖨️ Print / Save PDF
            </button>
          </div>
        </div>

        {/* Report Document */}
        <div className="report-document" id="report-doc">
          {/* Report Header */}
          <div className="report-header">
            <div className="report-logo">
              <span className="report-logo-icon">🩺</span>
              <div>
                <h1 className="report-brand">BodyMind AI</h1>
                <p className="report-brand-sub">Personal Health Intelligence Platform</p>
              </div>
            </div>
            <div className="report-meta">
              <div className="meta-item">
                <span className="meta-label">Report Generated</span>
                <span className="meta-value">{now.toLocaleDateString('en-US', { weekday:'long', year:'numeric', month:'long', day:'numeric' })}</span>
              </div>
              <div className="meta-item">
                <span className="meta-label">Report Period</span>
                <span className="meta-value">Last 7 Days</span>
              </div>
              <div className="meta-item">
                <span className="meta-label">Report ID</span>
                <span className="meta-value">BM-{Date.now().toString().slice(-8)}</span>
              </div>
            </div>
          </div>

          {/* Disclaimer */}
          <div className="disclaimer-banner">
            {DISCLAIMER}
          </div>

          {/* Section 1: Patient Profile */}
          <div className="report-section">
            <div className="section-header">
              <span className="section-num">01</span>
              <h2 className="section-heading">Patient Health Profile</h2>
            </div>
            <div className="profile-grid">
              {[
                ['Full Name', profile.name || 'Not provided'],
                ['Age', profile.age ? `${profile.age} years` : 'Not provided'],
                ['Gender', profile.gender || 'Not provided'],
                ['Blood Group', profile.bloodGroup || 'Not provided'],
                ['Body Type', profile.bodyType || 'Not provided'],
              ].map(([label, value]) => (
                <div key={label} className="profile-field">
                  <span className="field-label">{label}</span>
                  <span className="field-value">{value}</span>
                </div>
              ))}
            </div>

            {profile.preExistingConditions && (
              <div className="report-text-field">
                <span className="field-label">Pre-existing Conditions</span>
                <p className="field-text">{profile.preExistingConditions}</p>
              </div>
            )}
            {profile.allergies && (
              <div className="report-text-field">
                <span className="field-label">Known Allergies</span>
                <p className="field-text">{profile.allergies}</p>
              </div>
            )}
            {profile.currentMedications && (
              <div className="report-text-field">
                <span className="field-label">Current Medications</span>
                <p className="field-text">{profile.currentMedications}</p>
              </div>
            )}
            {profile.familyHistory && (
              <div className="report-text-field">
                <span className="field-label">Family Medical History</span>
                <p className="field-text">{profile.familyHistory}</p>
              </div>
            )}
          </div>

          {/* Section 2: Body Symptoms */}
          <div className="report-section">
            <div className="section-header">
              <span className="section-num">02</span>
              <h2 className="section-heading">Body Symptoms — Last 7 Days</h2>
            </div>
            {recentSymptoms.length === 0 ? (
              <p className="no-data">No body symptoms recorded in the last 7 days.</p>
            ) : (
              <>
                {/* Visual body map showing affected parts */}
                <div className="body-map-summary">
                  <p className="body-map-label">Affected Body Regions</p>
                  <div className="affected-parts">
                    {[...new Set(recentSymptoms.map(s => s.bodyPart))].map(part => (
                      <div key={part} className="affected-tag">
                        {part.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Symptom table */}
                <table className="report-table">
                  <thead>
                    <tr>
                      <th>Date & Time</th>
                      <th>Body Region</th>
                      <th>Pain Intensity</th>
                      <th>Duration</th>
                      <th>AI Diagnosis</th>
                    </tr>
                  </thead>
                  <tbody>
                    {recentSymptoms.map((s, i) => (
                      <tr key={i}>
                        <td>{new Date(s.date).toLocaleDateString()} {new Date(s.date).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</td>
                        <td>{s.bodyPart?.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}</td>
                        <td>
                          <span className={`pain-indicator ${s.painIntensity > 7 ? 'high' : s.painIntensity > 4 ? 'mid' : 'low'}`}>
                            {s.painIntensity}/10
                          </span>
                        </td>
                        <td>{s.duration?.replace(/-/g,' ')}</td>
                        <td>{s.aiDiagnosis || '—'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </>
            )}
          </div>

          {/* Section 3: Mind Module */}
          <div className="report-section">
            <div className="section-header">
              <span className="section-num">03</span>
              <h2 className="section-heading">Mental Health Assessment Summary</h2>
            </div>
            {recentMind.length === 0 ? (
              <p className="no-data">No mental health assessments recorded.</p>
            ) : (
              <>
                {mindAvg && (
                  <div className="mind-avg-grid">
                    {[
                      {label:'Average Mood', value:`${mindAvg.mood}/10`, color: mindAvg.mood < 4 ? '#ef4444' : mindAvg.mood < 7 ? '#facc15' : '#4ade80'},
                      {label:'Average Sleep', value:`${mindAvg.sleep}/10`, color: mindAvg.sleep < 4 ? '#ef4444' : mindAvg.sleep < 7 ? '#facc15' : '#4ade80'},
                      {label:'Average Stress', value:`${mindAvg.stress}/10`, color: mindAvg.stress > 7 ? '#ef4444' : mindAvg.stress > 4 ? '#facc15' : '#4ade80'},
                    ].map(m => (
                      <div key={m.label} className="mind-avg-card">
                        <span className="mind-avg-value" style={{color: m.color}}>{m.value}</span>
                        <span className="mind-avg-label">{m.label}</span>
                      </div>
                    ))}
                  </div>
                )}
                <table className="report-table" style={{marginTop:'16px'}}>
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Mood</th>
                      <th>Sleep</th>
                      <th>Stress</th>
                      <th>Focus</th>
                    </tr>
                  </thead>
                  <tbody>
                    {recentMind.map((m, i) => (
                      <tr key={i}>
                        <td>{new Date(m.date).toLocaleDateString()}</td>
                        <td><span className={`pain-indicator ${m.mood < 4 ? 'high' : m.mood < 7 ? 'mid' : 'low'}`}>{m.mood}/10</span></td>
                        <td><span className={`pain-indicator ${m.sleep < 4 ? 'high' : m.sleep < 7 ? 'mid' : 'low'}`}>{m.sleep}/10</span></td>
                        <td><span className={`pain-indicator ${m.stress > 7 ? 'high' : m.stress > 4 ? 'mid' : 'low'}`}>{m.stress}/10</span></td>
                        <td style={{textTransform:'capitalize'}}>{m.concentrate || '—'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </>
            )}
          </div>

          {/* Section 4: Medications suggested */}
          <div className="report-section">
            <div className="section-header">
              <span className="section-num">04</span>
              <h2 className="section-heading">AI-Suggested Medications</h2>
            </div>
            <div className="meds-disclaimer">
              ⚠️ These are general OTC suggestions based on AI analysis. Do NOT take any medication without consulting your doctor first.
            </div>
            {recentSymptoms.length === 0 ? (
              <p className="no-data">No symptoms recorded — no medications to suggest.</p>
            ) : (
              <div className="meds-list">
                {[...new Set(recentSymptoms.map(s => s.bodyPart))].map(part => (
                  <div key={part} className="med-group">
                    <h4 className="med-group-title">{part.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase())} Region</h4>
                    <p className="med-group-sub">Consult a doctor for appropriate prescription</p>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="report-footer">
            <div className="footer-logo">BodyMind AI — Personal Health Intelligence</div>
            <div className="footer-disclaimer">
              This document is NOT a medical prescription. Generated on {now.toLocaleDateString()} for informational purposes only.
              Always seek professional medical advice for diagnosis and treatment.
            </div>
            <div className="footer-meta">
              BodyMind AI v1.0 • Report ID: BM-{Date.now().toString().slice(-8)} • Confidential Patient Data
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
